using NexusForever.Game.Abstract.Entity;

namespace NexusForever.Game.Party
{
    /// <summary>
    /// A set of players that share rewards generated by the same combat contribution.
    /// A party id of zero represents a single, ungrouped participant.
    /// </summary>
    public sealed record PartyRewardGroup(
        ulong PartyId,
        IReadOnlyList<IPlayer> Contributors,
        IReadOnlyList<IPlayer> Members);
}
